// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CatDocumentDataSlicesSlice = CatInfoSlice;

/**
 * Content for cat documents
 */
interface CatDocumentData {
  /**
   * Slice Zone field in *cat*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cat.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CatDocumentDataSlicesSlice> /**
   * Meta Description field in *cat*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: cat.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *cat*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cat.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *cat*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: cat.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * cat document from Prismic
 *
 * - **API ID**: `cat`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CatDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<CatDocumentData>, "cat", Lang>;

export type AllDocumentTypes = CatDocument;

/**
 * Item in *CatInfo → Default → Primary → gallery*
 */
export interface CatInfoSliceDefaultPrimaryGalleryItem {
  /**
   * gallery img  field in *CatInfo → Default → Primary → gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.gallery[].gallery_img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gallery_img: prismic.ImageField<never>;
}

/**
 * Primary content in *CatInfo → Default → Primary*
 */
export interface CatInfoSliceDefaultPrimary {
  /**
   * h1 title field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.h1_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  h1_title: prismic.KeyTextField;

  /**
   * sub title field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  // sub_title: prismic.KeyTextField;

  /**
   * img1 catlog field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.img1_catalog
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img1_catalog: prismic.ImageField<never>;

  /**
   * img2 mobile field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.img2_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img2_mobile: prismic.ImageField<never>;

  /**
   * img3 desktop field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.img3_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img3_desktop: prismic.ImageField<never>;

  /**
   * gallery field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.gallery[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<CatInfoSliceDefaultPrimaryGalleryItem>>;

  /**
   * price field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * age field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.age
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  age: prismic.KeyTextField;

  /**
   * gender field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Male
   * - **API ID Path**: cat_info.default.primary.gender
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  gender: prismic.SelectField<"Male" | "Female" | "Bisexual :)", "filled">;

  /**
   * short description field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  short_description: prismic.KeyTextField;

  /**
   * status field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Available
   * - **API ID Path**: cat_info.default.primary.status
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  status: prismic.SelectField<"Available" | "Reserved" | "Sold", "filled">;

  /**
   * html description field in *CatInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cat_info.default.primary.html_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  html_description: prismic.KeyTextField;
}

/**
 * Default variation for CatInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CatInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CatInfo*
 */
type CatInfoSliceVariation = CatInfoSliceDefault;

/**
 * CatInfo Shared Slice
 *
 * - **API ID**: `cat_info`
 * - **Description**: CatInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CatInfoSlice = prismic.SharedSlice<
  "cat_info",
  CatInfoSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CatDocument,
      CatDocumentData,
      CatDocumentDataSlicesSlice,
      AllDocumentTypes,
      CatInfoSlice,
      CatInfoSliceDefaultPrimaryGalleryItem,
      CatInfoSliceDefaultPrimary,
      CatInfoSliceVariation,
      CatInfoSliceDefault,
    };
  }
}
